# Generated by Django 5.1.15 on 2025-12-15 15:43

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.JSONField(
                        help_text="Event title in multiple languages: {'pl': '', 'en': '', 'uk': ''}"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "description",
                    models.JSONField(
                        help_text="Event description in multiple languages"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONCERT", "Koncert"),
                            ("FESTIVAL", "Festiwal"),
                            ("THEATRE", "Teatr"),
                            ("CINEMA", "Kino"),
                            ("WORKSHOP", "Warsztat"),
                            ("FOOD", "Event kulinarny"),
                            ("CULTURAL", "Event kulturalny"),
                        ],
                        default="CULTURAL",
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("EVENT", "Event"),
                            ("PRODUCT", "Produkt"),
                            ("WORKSHOP", "Warsztat"),
                        ],
                        default="EVENT",
                        help_text="Event type: Event, Product, or Workshop",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        help_text="Town/village name (e.g., Ustrzyki Dolne)",
                        max_length=255,
                    ),
                ),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Geographic coordinates (longitude, latitude)",
                        srid=4326,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "price_type",
                    models.CharField(
                        choices=[("FREE", "Darmowy"), ("PAID", "Płatny")],
                        default="FREE",
                        max_length=10,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="PLN", max_length=3)),
                (
                    "age_restriction",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimum age (e.g., 18)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("organizer_name", models.CharField(max_length=255)),
                (
                    "organizer_contact",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contact info: email, phone, website",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, help_text="Event website"),
                ),
                (
                    "ticket_url",
                    models.URLField(blank=True, help_text="Ticket purchase link"),
                ),
                (
                    "facebook_event_id",
                    models.CharField(
                        blank=True,
                        help_text="Facebook event ID (for scraped events)",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Main event image",
                        null=True,
                        upload_to="events/",
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of additional image URLs",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Ręcznie dodany"),
                            ("SCRAPED", "Zescrapowany"),
                            ("USER_SUBMITTED", "Dodany przez użytkownika"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Oczekuje"),
                            ("APPROVED", "Zatwierdzony"),
                            ("REJECTED", "Odrzucony"),
                        ],
                        default="APPROVED",
                        max_length=20,
                    ),
                ),
                ("moderation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date"], name="events_even_start_d_d4b514_idx"
                    ),
                    models.Index(
                        fields=["category"], name="events_even_categor_aca11d_idx"
                    ),
                    models.Index(
                        fields=["moderation_status"],
                        name="events_even_moderat_e20938_idx",
                    ),
                    models.Index(
                        fields=["location_name"], name="events_even_locatio_0f2b7e_idx"
                    ),
                ],
            },
        ),
    ]
