# Generated by Django 5.1.15 on 2025-12-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nazwa organizatora", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Opis organizatora"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Zdjęcie główne organizatora",
                        null=True,
                        upload_to="organizers/images/",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo organizatora",
                        null=True,
                        upload_to="organizers/logos/",
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(
                        blank=True, help_text="Link do strony/grupy na Facebooku"
                    ),
                ),
                (
                    "ticketing_site",
                    models.URLField(blank=True, help_text="Link do strony z biletami"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Strona internetowa organizatora"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Czy organizator jest aktywny"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organizator",
                "verbose_name_plural": "Organizatorzy",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_name",
            field=models.CharField(
                blank=True,
                help_text="Nazwa organizatora (używane gdy brak powiązanego organizatora)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                help_text="Powiązany organizator",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.organizer",
            ),
        ),
    ]
