# Generated by Django 5.1.15 on 2026-01-05 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_organizer_alter_event_organizer_name_event_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="shortname",
            field=models.CharField(
                blank=True,
                help_text="Krótka nazwa organizatora (np. skrót lub nazwa wyświetlana)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="duration_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="DEPRECATED: Użyj EventDate model zamiast tego",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="DEPRECATED: Użyj EventDate model zamiast tego",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="DEPRECATED: Użyj EventDate model zamiast tego",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EventDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Data i godzina rozpoczęcia"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data i godzina zakończenia (opcjonalne)",
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Czas trwania w minutach",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Dodatkowe informacje o tym terminie (np. 'Dodatkowy koncert')",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Wydarzenie do którego należy ta data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_dates",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termin wydarzenia",
                "verbose_name_plural": "Terminy wydarzeń",
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date"], name="events_even_start_d_ad36ec_idx"
                    ),
                    models.Index(
                        fields=["event", "start_date"],
                        name="events_even_event_i_a5ff22_idx",
                    ),
                ],
            },
        ),
    ]
