# Generated by Django 5.1.15 on 2026-01-28 20:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_organizer_shortname_alter_event_duration_minutes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organizer_contact",
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizer_name",
        ),
        migrations.AlterField(
            model_name="event",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Geographic coordinates (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location_name",
            field=models.CharField(
                blank=True,
                help_text="Town/village name (e.g., Ustrzyki Dolne)",
                max_length=255,
                null=True,
            ),
        ),
    ]
