# Generated by Django 5.1.15 on 2026-01-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_remove_event_organizer_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="title",
        ),
        migrations.AddField(
            model_name="event",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="Event description in English (rich text)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description_pl",
            field=models.TextField(
                blank=True, help_text="Event description in Polish (rich text)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description_uk",
            field=models.TextField(
                blank=True, help_text="Event description in Ukrainian (rich text)"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Event title in English",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_pl",
            field=models.CharField(
                blank=True, help_text="Event title in Polish", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_uk",
            field=models.CharField(
                blank=True,
                help_text="Event title in Ukrainian",
                max_length=500,
                null=True,
            ),
        ),
    ]
