# Generated by Django 5.1.15 on 2026-01-28 21:14

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_remove_event_image_remove_event_images_eventimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name (e.g., Centrum Kultury, Bieszczadzki Dom Kultury)",
                        max_length=255,
                    ),
                ),
                (
                    "shortname",
                    models.CharField(
                        blank=True,
                        help_text="Short name for lists (e.g., CK, BDK)",
                        max_length=100,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Full address (ulica, numer, kod pocztowy, miasto)",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="City name (e.g., Ustrzyki Dolne)",
                        max_length=100,
                    ),
                ),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Geographic coordinates (longitude, latitude)",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "google_maps_url",
                    models.URLField(
                        blank=True, help_text="Google Maps link to location"
                    ),
                ),
                ("website", models.URLField(blank=True, help_text="Location website")),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone", max_length=50
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email", max_length=254
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum capacity (optional)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("VENUE", "Obiekt/ sala"),
                            ("OUTDOOR", "Plener"),
                            ("PRIVATE", "Prywatne"),
                            ("VIRTUAL", "Online"),
                        ],
                        default="VENUE",
                        help_text="Type of location",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional information about the location",
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of amenities: ['parking', 'wifi', 'accessible', 'bar', 'ac']",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this location can be used for new events",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lokalizacja",
                "verbose_name_plural": "Lokalizacje",
                "ordering": ["city", "name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="event",
            name="events_even_locatio_0f2b7e_idx",
        ),
        migrations.RemoveField(
            model_name="event",
            name="address",
        ),
        migrations.RemoveField(
            model_name="event",
            name="coordinates",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location_name",
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["city", "name"], name="events_loca_city_9853e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_active"], name="events_loca_is_acti_317d03_idx"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Miejsce wydarzenia",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.location",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["location"], name="events_even_locatio_b471aa_idx"
            ),
        ),
    ]
