# Generated by Django 5.1.15 on 2026-01-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0007_location_remove_event_events_even_locatio_0f2b7e_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="coordinates",
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitude (e.g., 49.4234)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitude (e.g., 22.5678)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
