# Generated by Django 5.1.15 on 2026-01-30 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_remove_location_coordinates_location_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdate",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Miejsce wydarzenia dla tego terminu",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_dates",
                to="events.location",
            ),
        ),
        migrations.AddIndex(
            model_name="eventdate",
            index=models.Index(
                fields=["location"], name="events_even_locatio_c3cff9_idx"
            ),
        ),
    ]
