# Generated by Django 6.0 on 2025-01-10 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tytuł obrazu', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Opis obrazu (opcjonalnie)')),
                ('image', models.ImageField(help_text='Plik obrazu', upload_to='gallery/')),
                ('tags', models.JSONField(blank=True, default=list, help_text="Lista tagów: ['landscape', 'nature', 'mountains']")),
                ('file_size', models.IntegerField(blank=True, help_text='Rozmiar pliku w bajtach', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.IntegerField(blank=True, help_text='Szerokość obrazu w pikselach', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.IntegerField(blank=True, help_text='Wysokość obrazu w pikselach', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obraz',
                'verbose_name_plural': 'Obrazy',
                'ordering': ['-uploaded_at'],
                'indexes': [
                    models.Index(fields=['uploaded_at'], name='gallery_im_upload_idx'),
                ],
            },
        ),
    ]
