# Generated by Django 5.1.15 on 2026-01-10 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="image",
            new_name="gallery_ima_uploade_e388d4_idx",
            old_name="gallery_im_upload_idx",
        ),
    ]
